export const cities = [
  // Thành phố trực thuộc Trung ương
  "Hà Nội",
  "Hồ Chí Minh",
  "Đà Nẵng",
  "Hải Phòng",
  "Cần Thơ",
  
  // Các thành phố trực thuộc tỉnh
  "Bà Rịa",
  "Bạc Liêu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bắc Ninh",
  "Bến Tre",
  "Biên Hòa",
  "Buôn Ma Thuột",
  "Cà Mau",
  "Cẩm Phả",
  "Cao Bằng",
  "Cao Lãnh",
  "Châu Đốc",
  "Đà Lạt",
  "Điện Biên Phủ",
  "Đông Hà",
  "Đồng Hới",
  "Hà Tĩnh",
  "Hạ Long",
  "Hải Dương",
  "Hòa Bình",
  "Hội An",
  "Huế",
  "Hưng Yên",
  "Kon Tum",
  "Lai Châu",
  "Lạng Sơn",
  "Lào Cai",
  "Long Xuyên",
  "Móng Cái",
  "Mỹ Tho",
  "Nam Định",
  "Ninh Bình",
  "Nha Trang",
  "Phan Rang","Tháp Chàm",
  "Phan Thiết",
  "Phủ Lý",
  "Pleiku",
  "Quảng Ngãi",
  "Quy Nhơn",
  "Rạch Giá",
  "Sa Đéc",
  "Sầm Sơn",
  "Sóc Trăng",
  "Sơn La",
  "Tam Kỳ",
  "Tân An",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Trà Vinh",
  "Tuy Hòa",
  "Tuyên Quang",
  "Uông Bí",
  "Việt Trì",
  "Vinh",
  "Vĩnh Long",
  "Vĩnh Yên",
  "Vũng Tàu",
  "Yên Bái",
  
  // Tỉnh/thành phố khác
  "Khác"
];